export type SeedProduct = {
  slug: string;
  name: string;
  category: "gaming" | "refurbished";
  brand: string;
  price: number;
  originalPrice?: number;
  specs: {
    cpu?: string;
    gpu?: string;
    ram?: string;
    storage?: string;
    display?: string;
  };
  conditionGrade?: "Good" | "Very Good" | "Excellent";
  images: string[];
  featured: boolean;
  inStock: boolean;
};

export const seedProducts: SeedProduct[] = [
  // ---- Gaming laptops (trending in the Indian market) ----
  {
    slug: "asus-rog-strix-g16",
    name: "ASUS ROG Strix G16",
    category: "gaming",
    brand: "ASUS",
    price: 115990,
    originalPrice: 129990,
    specs: {
      cpu: "Intel Core i7-13650HX",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "16\" QHD+ 165Hz",
    },
    images: ["/placeholders/asus-rog-strix-g16.svg"],
    featured: true,
    inStock: true,
  },
  {
    slug: "acer-nitro-v-15",
    name: "Acer Nitro V 15",
    category: "gaming",
    brand: "Acer",
    price: 64990,
    originalPrice: 71990,
    specs: {
      cpu: "Intel Core i5-13420H",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 144Hz",
    },
    images: ["/placeholders/acer-nitro-v-15.svg"],
    featured: true,
    inStock: true,
  },
  {
    slug: "lenovo-loq-15",
    name: "Lenovo LOQ 15",
    category: "gaming",
    brand: "Lenovo",
    price: 69990,
    originalPrice: 77990,
    specs: {
      cpu: "Intel Core i5-12450HX",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 144Hz",
    },
    images: ["/placeholders/lenovo-loq-15.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "hp-victus-15",
    name: "HP Victus 15",
    category: "gaming",
    brand: "HP",
    price: 65990,
    originalPrice: 72990,
    specs: {
      cpu: "AMD Ryzen 5 7535HS",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 144Hz",
    },
    images: ["/placeholders/hp-victus-15.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "msi-cyborg-15",
    name: "MSI Cyborg 15",
    category: "gaming",
    brand: "MSI",
    price: 67990,
    originalPrice: 74990,
    specs: {
      cpu: "Intel Core i5-13420H",
      gpu: "NVIDIA GeForce RTX 4050 6GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 144Hz",
    },
    images: ["/placeholders/msi-cyborg-15.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "dell-g15-5530",
    name: "Dell G15 5530",
    category: "gaming",
    brand: "Dell",
    price: 79990,
    originalPrice: 89990,
    specs: {
      cpu: "Intel Core i7-13650HX",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 120Hz",
    },
    images: ["/placeholders/dell-g15-5530.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "asus-tuf-a15",
    name: "ASUS TUF Gaming A15",
    category: "gaming",
    brand: "ASUS",
    price: 74990,
    originalPrice: 84990,
    specs: {
      cpu: "AMD Ryzen 7 7735HS",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      ram: "16GB DDR5",
      storage: "512GB SSD",
      display: "15.6\" FHD 144Hz",
    },
    images: ["/placeholders/asus-tuf-a15.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "acer-predator-helios-neo-16",
    name: "Acer Predator Helios Neo 16",
    category: "gaming",
    brand: "Acer",
    price: 124990,
    originalPrice: 139990,
    specs: {
      cpu: "Intel Core i7-13700HX",
      gpu: "NVIDIA GeForce RTX 4060 8GB",
      ram: "16GB DDR5",
      storage: "1TB SSD",
      display: "16\" WQXGA 165Hz",
    },
    images: ["/placeholders/acer-predator-helios-neo-16.svg"],
    featured: false,
    inStock: true,
  },

  // ---- Refurbished laptops ----
  {
    slug: "dell-latitude-7400",
    name: "Dell Latitude 7400",
    category: "refurbished",
    brand: "Dell",
    price: 18999,
    originalPrice: 34990,
    conditionGrade: "Very Good",
    specs: {
      cpu: "Intel Core i7-8665U (8th Gen)",
      ram: "16GB DDR4",
      storage: "512GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/dell-latitude-7400.svg"],
    featured: true,
    inStock: true,
  },
  {
    slug: "lenovo-thinkpad-t470",
    name: "Lenovo ThinkPad T470",
    category: "refurbished",
    brand: "Lenovo",
    price: 13999,
    originalPrice: 26990,
    conditionGrade: "Good",
    specs: {
      cpu: "Intel Core i5-6300U (6th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/lenovo-thinkpad-t470.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "hp-elitebook-840-g5",
    name: "HP EliteBook 840 G5",
    category: "refurbished",
    brand: "HP",
    price: 16999,
    originalPrice: 31990,
    conditionGrade: "Very Good",
    specs: {
      cpu: "Intel Core i5-8350U (8th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/hp-elitebook-840-g5.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "dell-latitude-5300",
    name: "Dell Latitude 5300",
    category: "refurbished",
    brand: "Dell",
    price: 17999,
    originalPrice: 32990,
    conditionGrade: "Excellent",
    specs: {
      cpu: "Intel Core i5-8365U (8th Gen)",
      ram: "16GB DDR4",
      storage: "256GB SSD",
      display: "13.3\" FHD",
    },
    images: ["/placeholders/dell-latitude-5300.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "lenovo-thinkpad-x1-carbon-g6",
    name: "Lenovo ThinkPad X1 Carbon Gen 6",
    category: "refurbished",
    brand: "Lenovo",
    price: 21999,
    originalPrice: 39990,
    conditionGrade: "Excellent",
    specs: {
      cpu: "Intel Core i5-8350U (8th Gen)",
      ram: "16GB DDR4",
      storage: "256GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/lenovo-thinkpad-x1-carbon-g6.svg"],
    featured: true,
    inStock: true,
  },
  {
    slug: "hp-probook-450-g6",
    name: "HP ProBook 450 G6",
    category: "refurbished",
    brand: "HP",
    price: 15999,
    originalPrice: 28990,
    conditionGrade: "Good",
    specs: {
      cpu: "Intel Core i5-8265U (8th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "15.6\" FHD",
    },
    images: ["/placeholders/hp-probook-450-g6.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "dell-latitude-7480",
    name: "Dell Latitude 7480",
    category: "refurbished",
    brand: "Dell",
    price: 14999,
    originalPrice: 27990,
    conditionGrade: "Good",
    specs: {
      cpu: "Intel Core i5-7300U (7th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/dell-latitude-7480.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "lenovo-thinkpad-t480",
    name: "Lenovo ThinkPad T480",
    category: "refurbished",
    brand: "Lenovo",
    price: 16999,
    originalPrice: 30990,
    conditionGrade: "Very Good",
    specs: {
      cpu: "Intel Core i5-8350U (8th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "14\" FHD",
    },
    images: ["/placeholders/lenovo-thinkpad-t480.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "hp-elitebook-830-g5",
    name: "HP EliteBook 830 G5",
    category: "refurbished",
    brand: "HP",
    price: 17499,
    originalPrice: 32990,
    conditionGrade: "Very Good",
    specs: {
      cpu: "Intel Core i5-8250U (8th Gen)",
      ram: "8GB DDR4",
      storage: "256GB SSD",
      display: "13.3\" FHD",
    },
    images: ["/placeholders/hp-elitebook-830-g5.svg"],
    featured: false,
    inStock: true,
  },
  {
    slug: "microsoft-surface-laptop-2",
    name: "Microsoft Surface Laptop 2",
    category: "refurbished",
    brand: "Microsoft",
    price: 19999,
    originalPrice: 36990,
    conditionGrade: "Excellent",
    specs: {
      cpu: "Intel Core i5-8250U (8th Gen)",
      ram: "8GB LPDDR3",
      storage: "256GB SSD",
      display: "13.5\" PixelSense",
    },
    images: ["/placeholders/microsoft-surface-laptop-2.svg"],
    featured: false,
    inStock: true,
  },
];
